# Site settings
title: Eisach's Page
author:
  name: Eisach
  email: eisach.yambao@dhl.com
description: "Application Support at DHL Information Services"

# Build settings
remote_theme: jekyll/minima
